/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kradac.despachos.interfaz;

import com.kradac.despachos.database.DataBase;
import com.kradac.despachos.reportes.GenerarReporteClientes;
import com.kradac.despachos.reportes.GenerarReporteDespachos;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

public class FrameReports extends javax.swing.JFrame {

    private final DataBase db;
    SimpleDateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat formatTime = new SimpleDateFormat("HH:mm:ss");
    GregorianCalendar gc = new GregorianCalendar();

    public FrameReports() {
        initComponents();
        db = new DataBase(Principal.fileConfig, Principal.numHost);
        cargarComboUsuarios();
        
        JFormattedTextField textField = ((JSpinner.DefaultEditor) jsTimeStart.getEditor()).getTextField();
        JFormattedTextField textField2 = ((JSpinner.DefaultEditor) jsTimeFinish.getEditor()).getTextField();

        DefaultFormatterFactory dff = (DefaultFormatterFactory) textField.getFormatterFactory();
        DefaultFormatterFactory dff2 = (DefaultFormatterFactory) textField2.getFormatterFactory();

        DateFormatter formatter = (DateFormatter) dff.getDefaultFormatter();
        DateFormatter formatter2 = (DateFormatter) dff2.getDefaultFormatter();
        
        formatter.setFormat(formatTime);
        formatter2.setFormat(formatTime);
        
        jsTimeStart.setValue(gc.getTime());
        jsTimeFinish.setValue(gc.getTime());
        
        jdFechaIniDia.setFormats(formatDate);
        jdFechaIniDia.setDate(gc.getTime());
        
        jdFechaIniDes.setFormats(formatDate);
        jdFechaIniDes.setDate(gc.getTime());
        jdFechaFinDes.setFormats(formatDate);
        jdFechaFinDes.setDate(gc.getTime());
        
        jpFechas.setVisible(false);
        jpHoras.setVisible(false);
    }

    private void cargarComboUsuarios() {

        String[] usuarios = db.getUsuarios();
        for (String user : usuarios) {
            jcUsuariosDespachos.addItem(user);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgCli = new javax.swing.ButtonGroup();
        btgDes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        JTabReporte = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        rCodCli = new javax.swing.JRadioButton();
        textCodCli = new javax.swing.JTextField();
        rTelCli = new javax.swing.JRadioButton();
        textTelCli = new javax.swing.JTextField();
        rNomCli = new javax.swing.JRadioButton();
        textNomCli = new javax.swing.JTextField();
        rTodoCli = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rCarrerasPorDia = new javax.swing.JRadioButton();
        rDespachosTurno = new javax.swing.JRadioButton();
        jcUsuariosDespachos = new javax.swing.JComboBox();
        jdFechaIniDia = new org.jdesktop.swingx.JXDatePicker();
        jpFechas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jdFechaIniDes = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        jdFechaFinDes = new org.jdesktop.swingx.JXDatePicker();
        jpHoras = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jsTimeStart = new javax.swing.JSpinner();
        jsTimeFinish = new javax.swing.JSpinner();
        rCarrerasFechHor = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnGenerar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        btgCli.add(rCodCli);
        btgCli.add(rTelCli);

        btgDes.add(rDespachosTurno);
        btgDes.add(rCarrerasPorDia);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/kradac/despachos/img/reporte.png")).getImage());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Reportes");

        JTabReporte.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JTabReporteAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btgCli.add(rCodCli);
        rCodCli.setText("Codigo Cliente:");
        rCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCodCliActionPerformed(evt);
            }
        });

        textCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodCliActionPerformed(evt);
            }
        });
        textCodCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCodCliFocusLost(evt);
            }
        });

        btgCli.add(rTelCli);
        rTelCli.setText("Telefono:");
        rTelCli.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rTelCliStateChanged(evt);
            }
        });
        rTelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTelCliActionPerformed(evt);
            }
        });

        textTelCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textTelCliFocusLost(evt);
            }
        });

        btgCli.add(rNomCli);
        rNomCli.setText("Nombre Cliente:");

        btgCli.add(rTodoCli);
        rTodoCli.setText("Todos los clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rTodoCli)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rCodCli)
                            .addComponent(rTelCli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textCodCli)
                            .addComponent(textTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rNomCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(rTodoCli)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCodCli)
                    .addComponent(textCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rTelCli)
                    .addComponent(textTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rNomCli)
                    .addComponent(textNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        JTabReporte.addTab("Clientes", new javax.swing.ImageIcon(getClass().getResource("/com/kradac/despachos/img/usuario.png")), jPanel1); // NOI18N

        btgDes.add(rCarrerasPorDia);
        rCarrerasPorDia.setText("Carreras del dia:");
        rCarrerasPorDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCarrerasPorDiaActionPerformed(evt);
            }
        });

        btgDes.add(rDespachosTurno);
        rDespachosTurno.setText("Usuario");
        rDespachosTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDespachosTurnoActionPerformed(evt);
            }
        });

        jcUsuariosDespachos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcUsuariosDespachos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcUsuariosDespachosActionPerformed(evt);
            }
        });

        jdFechaIniDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdFechaIniDiaActionPerformed(evt);
            }
        });

        jpFechas.setBorder(javax.swing.BorderFactory.createTitledBorder("Fechas"));
        jpFechas.setOpaque(false);

        jLabel2.setText("Inicio:");

        jdFechaIniDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdFechaIniDesActionPerformed(evt);
            }
        });

        jLabel5.setText("Fin:");

        javax.swing.GroupLayout jpFechasLayout = new javax.swing.GroupLayout(jpFechas);
        jpFechas.setLayout(jpFechasLayout);
        jpFechasLayout.setHorizontalGroup(
            jpFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFechasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdFechaIniDes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdFechaFinDes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFechasLayout.setVerticalGroup(
            jpFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFechasLayout.createSequentialGroup()
                .addGroup(jpFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jdFechaIniDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jdFechaFinDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpHoras.setBorder(javax.swing.BorderFactory.createTitledBorder("Horas"));
        jpHoras.setOpaque(false);

        jLabel3.setText("Inicio:");

        jLabel6.setText("Fin:");

        jsTimeStart.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));

        jsTimeFinish.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));

        javax.swing.GroupLayout jpHorasLayout = new javax.swing.GroupLayout(jpHoras);
        jpHoras.setLayout(jpHorasLayout);
        jpHorasLayout.setHorizontalGroup(
            jpHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHorasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsTimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsTimeFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpHorasLayout.setVerticalGroup(
            jpHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHorasLayout.createSequentialGroup()
                .addGroup(jpHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jsTimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsTimeFinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btgDes.add(rCarrerasFechHor);
        rCarrerasFechHor.setText("Entre");
        rCarrerasFechHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCarrerasFechHorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rCarrerasFechHor)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rDespachosTurno)
                            .addComponent(rCarrerasPorDia))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcUsuariosDespachos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdFechaIniDia, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpFechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCarrerasPorDia)
                    .addComponent(jdFechaIniDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDespachosTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcUsuariosDespachos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rCarrerasFechHor)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpFechas.getAccessibleContext().setAccessibleParent(jpFechas);
        jpHoras.getAccessibleContext().setAccessibleParent(jpHoras);

        JTabReporte.addTab("Carreras", new javax.swing.ImageIcon(getClass().getResource("/com/kradac/despachos/img/carreras.png")), jPanel2); // NOI18N

        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kradac/despachos/img/reporte.png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kradac/despachos/img/cancelar.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabReporte)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTabReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnGenerar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodCliActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        int idx = JTabReporte.getSelectedIndex();
        GenerarReporte(idx);
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void jcUsuariosDespachosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcUsuariosDespachosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcUsuariosDespachosActionPerformed

    private void rCarrerasPorDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCarrerasPorDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rCarrerasPorDiaActionPerformed

    private void rDespachosTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDespachosTurnoActionPerformed
        // TODO add your handling code here:
        if (rDespachosTurno.isSelected()) {
            jpFechas.setVisible(true);
            jpHoras.setVisible(true);
            jsTimeStart.setValue(gc.getTime());
            jsTimeFinish.setValue(gc.getTime());
        }
    }//GEN-LAST:event_rDespachosTurnoActionPerformed

    private void JTabReporteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JTabReporteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JTabReporteAncestorAdded

    private void jdFechaIniDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdFechaIniDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdFechaIniDiaActionPerformed

    private void jdFechaIniDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdFechaIniDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdFechaIniDesActionPerformed

    private void rCarrerasFechHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCarrerasFechHorActionPerformed
        // TODO add your handling code here:
        if (rCarrerasFechHor.isSelected()) {
            jpFechas.setVisible(true);
            jpHoras.setVisible(true);
        }
    }//GEN-LAST:event_rCarrerasFechHorActionPerformed

    private void rCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCodCliActionPerformed
        // TODO add your handling code here:
        if (rCodCli.isSelected()) {
            textTelCli.setText("");
            textTelCli.setEditable(false);
            textCodCli.setEditable(true);
        }

    }//GEN-LAST:event_rCodCliActionPerformed

    private void rTelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTelCliActionPerformed
        // TODO add your handling code here:
        if (rTelCli.isSelected()) {
            textCodCli.setText("");
            textCodCli.setEditable(false);
            textTelCli.setEditable(true);
        }
    }//GEN-LAST:event_rTelCliActionPerformed

    private void rTelCliStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rTelCliStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rTelCliStateChanged

    private void textCodCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCodCliFocusLost
        // TODO add your handling code here:
        if (!textCodCli.getText().equals("")) {
            try {
                Integer.parseInt(textCodCli.getText());
            } catch (NumberFormatException ex) {
                textCodCli.setText("");
                JOptionPane.showMessageDialog(this, "Solo se puede ingresar numeros...", "Error...", 0);
            }
        }
    }//GEN-LAST:event_textCodCliFocusLost

    private void textTelCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textTelCliFocusLost
        // TODO add your handling code here:
        if (!textTelCli.getText().equals("")) {
            try {
                Integer.parseInt(textTelCli.getText());
            } catch (NumberFormatException ex) {
                textTelCli.setText("");
                JOptionPane.showMessageDialog(this, "Solo se puede ingresar numeros...", "Error...", 0);
            }
        }
    }//GEN-LAST:event_textTelCliFocusLost

    /**
     * @param args the command line arguments
     */
    private HashMap getDatosCliente() {
        
        Date now = new Date(System.currentTimeMillis());
        
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        
         String fecha=date.format(now);
        
        
        HashMap map = new HashMap();
        String cod = textCodCli.getText();
        String tel = textTelCli.getText();
        String nom = textNomCli.getText();

        map.put("cod", cod);
        map.put("tel", tel);
        map.put("nom", nom);
        map.put("fechaIni", (date.format(now)));
        map.put("horaIni", (hour.format(now)));
        System.out.println(date.format(now).toString());
        System.out.println(hour.format(now).toString());

        if (rTodoCli.isSelected()) {
            map.put("todo", true);
        } else {
            map.put("todo", false);
        }
        return map;

    }

    /**
     * Obtiene los datos del formulario de despachos para generar el reporte
     *
     * @return HashMap
     */
    private HashMap getDatosDespacho() {
        HashMap map = new HashMap();

        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat dfFecha = new SimpleDateFormat("yyyy-MM-dd");

        String fechaIni = dfFecha.format(jdFechaIniDia.getDate());
        String fechaIniDes = dfFecha.format(jdFechaIniDes.getDate());
        String fechaFinDes = dfFecha.format(jdFechaFinDes.getDate());
        //String horaIni = txtHoraIni.getText();
        //String horaFin = txtHoraFin.getText();
        String usuario = jcUsuariosDespachos.getSelectedItem().toString();

        map.put("user", usuario);
        map.put("fechaIniDes", fechaIniDes);
        map.put("fechaFinDes", fechaFinDes);
        map.put("horaIni", formatTime.format((Date) jsTimeStart.getValue()));
        map.put("horaFin", formatTime.format((Date) jsTimeFinish.getValue()));
        map.put("fechaIni", fechaIni);
        try {
            map.put("nombre_user", this.db.getDatosUsuario(usuario).getString("id_user"));
        } catch (SQLException ex) {
            map.put("nombre_user", usuario);
        }

        if (rCarrerasPorDia.isSelected()) {
            
            map.put("todo", true);
        } else {
            map.put("todo", false);
        }

        if (rDespachosTurno.isSelected()) {
            if (!formatTime.format((Date) jsTimeStart.getValue()).equals("")) {
                map.put("turno", true);
            } else {
                map.put("turno", false);
            }

        } else {
            map.put("turno", false);
        }

        if (rCarrerasFechHor.isSelected()) {
            map.put("entre", true);
        } else {
            map.put("entre", false);
        }

        //map.put("turnotxt", jcTurnosDespachos.getSelectedItem().toString());
        return map;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabReporte;
    private javax.swing.ButtonGroup btgCli;
    private javax.swing.ButtonGroup btgDes;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox jcUsuariosDespachos;
    private org.jdesktop.swingx.JXDatePicker jdFechaFinDes;
    private org.jdesktop.swingx.JXDatePicker jdFechaIniDes;
    private org.jdesktop.swingx.JXDatePicker jdFechaIniDia;
    private javax.swing.JPanel jpFechas;
    private javax.swing.JPanel jpHoras;
    private javax.swing.JSpinner jsTimeFinish;
    private javax.swing.JSpinner jsTimeStart;
    private javax.swing.JRadioButton rCarrerasFechHor;
    private javax.swing.JRadioButton rCarrerasPorDia;
    private javax.swing.JRadioButton rCodCli;
    private javax.swing.JRadioButton rDespachosTurno;
    private javax.swing.JRadioButton rNomCli;
    private javax.swing.JRadioButton rTelCli;
    private javax.swing.JRadioButton rTodoCli;
    private javax.swing.JTextField textCodCli;
    private javax.swing.JTextField textNomCli;
    private javax.swing.JTextField textTelCli;
    // End of variables declaration//GEN-END:variables

    private void GenerarReporte(int idx) {
        switch (idx) {
            case 0:
                GenerarReporteClientes clientes = new GenerarReporteClientes(db, getDatosCliente());
                clientes.Generar();
                break;
            case 1:
                GenerarReporteDespachos despachos = new GenerarReporteDespachos(db, getDatosDespacho());
                despachos.Generar();
                break;
        }
    }
}
